// Code generated by the multiversx-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Upgrade:                              1
// Endpoints:                            6
// Async Callback (empty):               1
// Total number of exported functions:   9

#![no_std]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    rust_challenge
    (
        init => init
        upgrade => upgrade
        setFee => set_fee
        deposit => deposit
        withdraw => withdraw
        fee => fee
        getCollectedFees => collected_fees
        getReserveForAddress => reserve_for_address
    )
}

multiversx_sc_wasm_adapter::async_callback_empty! {}
