[package]
name = "basic-interact"
version = "0.0.0"
edition = "2021"
publish = false

[[bin]]
name = "basic-interact"
path = "src/basic_interact_main.rs"

[lib]
path = "src/basic_interact.rs"

[dependencies.rust-challenge]
path = ".."

[dependencies]
clap = { version = "4.4", features = ["derive"] }
serde = { version = "1.0", features = ["derive"] }
toml = "1.0"
tokio = { version = "1.24" }
serial_test = { version = "3.2.0" }

[dependencies.multiversx-sc-snippets]
version = "0.65.0"

[features]
chain-simulator-tests = []
